//
// This file was generated. DO NOT EDIT!
//

package tba

const (
	MATCH_LEVEL_TEST = 0
	MATCH_LEVEL_PRACTICE = 1
	MATCH_LEVEL_QUAL = 2
	MATCH_LEVEL_PLAYOFF = 3
	MATCH_LEVEL_MANUAL = 99
)

const (
	BRACKET_TYPE_BRACKET_8_TEAM = 0
	BRACKET_TYPE_BRACKET_16_TEAM = 1
	BRACKET_TYPE_BRACKET_4_TEAM = 2
	BRACKET_TYPE_AVG_SCORE_8_TEAM = 3
	BRACKET_TYPE_ROUND_ROBIN_6_TEAM = 4
	BRACKET_TYPE_LEGACY_DOUBLE_ELIM_8_TEAM = 5
	BRACKET_TYPE_BO5_FINALS = 6
	BRACKET_TYPE_BO3_FINALS = 7
	BRACKET_TYPE_CUSTOM = 8
	BRACKET_TYPE_BRACKET_2_TEAM = 9
	BRACKET_TYPE_DOUBLE_ELIM_8_TEAM = 10
	BRACKET_TYPE_DOUBLE_ELIM_4_TEAM = 11
	BRACKET_TYPE_X_KETTERING_ALLSTAR_8_TEAM = 1001
	BRACKET_TYPE_X_KETTERING_ALLSTAR_6_TEAM = 1002
)

const (
	BRACKET_NAME_BRACKET_8_TEAM = "Elimination Bracket (8 Alliances)"
	BRACKET_NAME_BRACKET_4_TEAM = "Elimination Bracket (4 Alliances)"
	BRACKET_NAME_BRACKET_16_TEAM = "Elimination Bracket (16 Alliances)"
	BRACKET_NAME_AVG_SCORE_8_TEAM = "Average Score (8 Alliances)"
	BRACKET_NAME_ROUND_ROBIN_6_TEAM = "Round Robin (6 Alliances)"
	BRACKET_NAME_LEGACY_DOUBLE_ELIM_8_TEAM = "Legacy Double Elimination Bracket (8 Alliances)"
	BRACKET_NAME_BO3_FINALS = "Best of 3 Finals"
	BRACKET_NAME_BO5_FINALS = "Best of 5 Finals"
	BRACKET_NAME_CUSTOM = "Custom"
	BRACKET_NAME_BRACKET_2_TEAM = "Elimination Bracket (2 Alliances)"
	BRACKET_NAME_DOUBLE_ELIM_8_TEAM = "Double Elimination Bracket (8 Alliances)"
	BRACKET_NAME_DOUBLE_ELIM_4_TEAM = "Double Elimination Bracket (4 Alliances)"
	BRACKET_NAME_X_KETTERING_ALLSTAR_8_TEAM = "[Custom] Kettering AllStar (8 Alliances)"
	BRACKET_NAME_X_KETTERING_ALLSTAR_6_TEAM = "[Custom] Kettering AllStar (6 Alliances)"
)

const (
	FIELD_STATE_WaitingForPrestart = 2
	FIELD_STATE_WaitingForPrestartTO = 3
	FIELD_STATE_Prestarting = 4
	FIELD_STATE_PrestartingTO = 5
	FIELD_STATE_WaitingForSetAudience = 6
	FIELD_STATE_WaitingForSetAudienceTO = 7
	FIELD_STATE_WaitingForMatchPreview = 18
	FIELD_STATE_WaitingForMatchPreviewTO = 19
	FIELD_STATE_WaitingForMatchReady = 8
	FIELD_STATE_WaitingForMatchStart = 9
	FIELD_STATE_GameSpecific = 10
	FIELD_STATE_MatchAuto = 11
	FIELD_STATE_MatchTransition = 12
	FIELD_STATE_MatchTeleop = 13
	FIELD_STATE_WaitingForCommit = 14
	FIELD_STATE_WaitingForPostResults = 15
	FIELD_STATE_TournamentLevelComplete = 16
	FIELD_STATE_MatchCancelled = 17
)

const (
	AWARD_TYPE_CHAIRMANS = 0
	AWARD_TYPE_WINNER = 1
	AWARD_TYPE_FINALIST = 2
	AWARD_TYPE_WOODIE_FLOWERS = 3
	AWARD_TYPE_DEANS_LIST = 4
	AWARD_TYPE_VOLUNTEER = 5
	AWARD_TYPE_FOUNDERS = 6
	AWARD_TYPE_BART_KAMEN_MEMORIAL = 7
	AWARD_TYPE_MAKE_IT_LOUD = 8
	AWARD_TYPE_ENGINEERING_INSPIRATION = 9
	AWARD_TYPE_ROOKIE_ALL_STAR = 10
	AWARD_TYPE_GRACIOUS_PROFESSIONALISM = 11
	AWARD_TYPE_COOPERTITION = 12
	AWARD_TYPE_JUDGES = 13
	AWARD_TYPE_HIGHEST_ROOKIE_SEED = 14
	AWARD_TYPE_ROOKIE_INSPIRATION = 15
	AWARD_TYPE_INDUSTRIAL_DESIGN = 16
	AWARD_TYPE_QUALITY = 17
	AWARD_TYPE_SAFETY = 18
	AWARD_TYPE_SPORTSMANSHIP = 19
	AWARD_TYPE_CREATIVITY = 20
	AWARD_TYPE_ENGINEERING_EXCELLENCE = 21
	AWARD_TYPE_ENTREPRENEURSHIP = 22
	AWARD_TYPE_EXCELLENCE_IN_DESIGN = 23
	AWARD_TYPE_EXCELLENCE_IN_DESIGN_CAD = 24
	AWARD_TYPE_EXCELLENCE_IN_DESIGN_ANIMATION = 25
	AWARD_TYPE_DRIVING_TOMORROWS_TECHNOLOGY = 26
	AWARD_TYPE_IMAGERY = 27
	AWARD_TYPE_MEDIA_AND_TECHNOLOGY = 28
	AWARD_TYPE_INNOVATION_IN_CONTROL = 29
	AWARD_TYPE_SPIRIT = 30
	AWARD_TYPE_WEBSITE = 31
	AWARD_TYPE_VISUALIZATION = 32
	AWARD_TYPE_AUTODESK_INVENTOR = 33
	AWARD_TYPE_FUTURE_INNOVATOR = 34
	AWARD_TYPE_RECOGNITION_OF_EXTRAORDINARY_SERVICE = 35
	AWARD_TYPE_OUTSTANDING_CART = 36
	AWARD_TYPE_WSU_AIM_HIGHER = 37
	AWARD_TYPE_LEADERSHIP_IN_CONTROL = 38
	AWARD_TYPE_NUM_1_SEED = 39
	AWARD_TYPE_INCREDIBLE_PLAY = 40
	AWARD_TYPE_PEOPLES_CHOICE_ANIMATION = 41
	AWARD_TYPE_VISUALIZATION_RISING_STAR = 42
	AWARD_TYPE_BEST_OFFENSIVE_ROUND = 43
	AWARD_TYPE_BEST_PLAY_OF_THE_DAY = 44
	AWARD_TYPE_FEATHERWEIGHT_IN_THE_FINALS = 45
	AWARD_TYPE_MOST_PHOTOGENIC = 46
	AWARD_TYPE_OUTSTANDING_DEFENSE = 47
	AWARD_TYPE_POWER_TO_SIMPLIFY = 48
	AWARD_TYPE_AGAINST_ALL_ODDS = 49
	AWARD_TYPE_RISING_STAR = 50
	AWARD_TYPE_CHAIRMANS_HONORABLE_MENTION = 51
	AWARD_TYPE_CONTENT_COMMUNICATION_HONORABLE_MENTION = 52
	AWARD_TYPE_TECHNICAL_EXECUTION_HONORABLE_MENTION = 53
	AWARD_TYPE_REALIZATION = 54
	AWARD_TYPE_REALIZATION_HONORABLE_MENTION = 55
	AWARD_TYPE_DESIGN_YOUR_FUTURE = 56
	AWARD_TYPE_DESIGN_YOUR_FUTURE_HONORABLE_MENTION = 57
	AWARD_TYPE_SPECIAL_RECOGNITION_CHARACTER_ANIMATION = 58
	AWARD_TYPE_HIGH_SCORE = 59
	AWARD_TYPE_TEACHER_PIONEER = 60
	AWARD_TYPE_BEST_CRAFTSMANSHIP = 61
	AWARD_TYPE_BEST_DEFENSIVE_MATCH = 62
	AWARD_TYPE_PLAY_OF_THE_DAY = 63
	AWARD_TYPE_PROGRAMMING = 64
	AWARD_TYPE_PROFESSIONALISM = 65
	AWARD_TYPE_GOLDEN_CORNDOG = 66
	AWARD_TYPE_MOST_IMPROVED_TEAM = 67
	AWARD_TYPE_WILDCARD = 68
	AWARD_TYPE_CHAIRMANS_FINALIST = 69
	AWARD_TYPE_OTHER = 70
	AWARD_TYPE_AUTONOMOUS = 71
	AWARD_TYPE_INNOVATION_CHALLENGE_SEMI_FINALIST = 72
	AWARD_TYPE_ROOKIE_GAME_CHANGER = 73
	AWARD_TYPE_SKILLS_COMPETITION_WINNER = 74
	AWARD_TYPE_SKILLS_COMPETITION_FINALIST = 75
	AWARD_TYPE_ROOKIE_DESIGN = 76
	AWARD_TYPE_ENGINEERING_DESIGN = 77
	AWARD_TYPE_DESIGNERS = 78
	AWARD_TYPE_CONCEPT = 79
	AWARD_TYPE_GAME_DESIGN_CHALLENGE_WINNER = 80
	AWARD_TYPE_GAME_DESIGN_CHALLENGE_FINALIST = 81
	AWARD_TYPE_SUSTAINABILITY = 82
)

